export const CommentConst = {
	CREATE: 'comment.create',
	INDEX: 'comment.index'
};

export const UserConst = {
	INDEX: 'user.index'
};

export const AuthConst = {
	'LOGIN': 'auth.login',
	'REGISTER': 'auth.register',
	'RESET': 'auth.reset',
	'LOGOUT': 'auth.logout'
};

export const POST = {
	CREATE_REQUEST: 'POST.CREATE_REQUEST',
	CREATE_SUCCESS: 'POST.CREATE_SUCCESS',
	CREATE_FAIL: 'POST.CREATE_FAIL',
	GET_ALL_REQUEST: 'POST.GET_ALL_REQUEST',
	GET_ALL_SUCCESS: 'POST.GET_ALL_SUCCESS',
	GET_ALL_FAIL: 'POST.GET_ALL_FAIL'
};

export const AUTH = {
	LOGIN_REQUEST: 'AUTH.LOGIN_REQUEST',
	LOGIN_SUCCESS: 'AUTH.LOGIN_SUCCESS',
	LOGIN_FAIL: 'AUTH.LOGIN_FAIL',
	REGISTER_REQUEST: 'AUTH.REGISTER_REQUEST',
	REGISTER_SUCCESS: 'AUTH.REGISTER_SUCCESS',
	REGISTER_FAIL: 'AUTH.REGISTER_FAIL',
	LOGOUT_REQUEST: 'AUTH.LOGOUT_REQUEST',
	LOGOUT_SUCCESS: 'AUTH.LOGOUT_SUCCESS'
}