export const URL_API = '//reactcomments.dev';

export const POST = {
	CREATE_REQUEST: 'POST.CREATE_REQUEST',
	CREATE_SUCCESS: 'POST.CREATE_SUCCESS',
	CREATE_FAILURE: 'POST.CREATE_FAILURE',
	GET_ALL_REQUEST: 'POST.GET_ALL_REQUEST',
	GET_ALL_SUCCESS: 'POST.GET_ALL_SUCCESS',
	GET_ALL_FAILURE: 'POST.GET_ALL_FAILURE'
};

export const AUTH = {
	LOGIN_REQUEST: 'AUTH.LOGIN_REQUEST',
	LOGIN_SUCCESS: 'AUTH.LOGIN_SUCCESS',
	LOGIN_FAILURE: 'AUTH.LOGIN_FAILURE',
	REGISTER_REQUEST: 'AUTH.REGISTER_REQUEST',
	REGISTER_SUCCESS: 'AUTH.REGISTER_SUCCESS',
	REGISTER_FAILURE: 'AUTH.REGISTER_FAILURE',
	LOGOUT_REQUEST: 'AUTH.LOGOUT_REQUEST',
	LOGOUT_SUCCESS: 'AUTH.LOGOUT_SUCCESS',
	LOGOUT_FAILURE: 'AUTH.LOGOUT_FAILURE',
	SET_TOKEN: 'AUTH.SET_TOKEN',
	GET_LOGGED_USER_REQUEST: 'AUTH.GET_LOGGED_USER_REQUEST',
	GET_LOGGED_USER_SUCCESS: 'AUTH.GET_LOGGED_USER_SUCCESS',
	RESET_STATE: 'AUTH.RESET_STATE'
};

export const CONVERSATION = {
	GET_BY_USER_REQUEST: 'CONVERSATION.GET_BY_USER_REQUEST',
	GET_BY_USER_SUCCESS: 'CONVERSATION.GET_BY_USER_SUCCESS',
	GET_BY_USER_FAILURE: 'CONVERSATION.GET_BY_USER_FAILURE',
	GET_MESSAGES_REQUEST: 'CONVERSATION.GET_MESSAGES_REQUEST',
	GET_MESSAGES_SUCCESS: 'CONVERSATION.GET_MESSAGES_SUCCESS',
	GET_MESSAGES_FAILURE: 'CONVERSATION.GET_MESSAGES_FAILURE',
	RESET: 'CONVERSATION.RESET',
	GET_LAST_ID_REQUEST: 'CONVERSATION.GET_LAST_ID_REQUEST',
	GET_LAST_ID_SUCCESS: 'CONVERSATION.GET_LAST_ID_SUCCESS',
	SEND_MESSAGE_REQUEST: 'CONVERSATION.SEND_MESSAGE_REQUEST', 
	SEND_MESSAGE_SUCCESS: 'CONVERSATION.SEND_MESSAGE_SUCCESS', 
	SEND_MESSAGE_FAILURE: 'CONVERSATION.SEND_MESSAGE_FAILURE'
};

export const APP = {
	FAILURE: 'APP.FAILURE',
	SET_TITLE: 'APP.SET_TITLE'
};