export const URL_API = '//reactcomments.dev';

export const POST = {
	CREATE_REQUEST: 'POST.CREATE_REQUEST',
	CREATE_SUCCESS: 'POST.CREATE_SUCCESS',
	CREATE_FAILURE: 'POST.CREATE_FAILURE',
	GET_ALL_REQUEST: 'POST.GET_ALL_REQUEST',
	GET_ALL_SUCCESS: 'POST.GET_ALL_SUCCESS',
	GET_ALL_FAILURE: 'POST.GET_ALL_FAILURE'
};

export const AUTH = {
	LOGIN_REQUEST: 'AUTH.LOGIN_REQUEST',
	LOGIN_SUCCESS: 'AUTH.LOGIN_SUCCESS',
	LOGIN_FAILURE: 'AUTH.LOGIN_FAILURE',
	REGISTER_REQUEST: 'AUTH.REGISTER_REQUEST',
	REGISTER_SUCCESS: 'AUTH.REGISTER_SUCCESS',
	REGISTER_FAIL: 'AUTH.REGISTER_FAIL',
	LOGOUT_REQUEST: 'AUTH.LOGOUT_REQUEST',
	LOGOUT_SUCCESS: 'AUTH.LOGOUT_SUCCESS'
};

export const CONVERSATION = {
	GET_BY_USER_REQUEST: 'CONVERSATION.GET_BY_USER_REQUEST',
	GET_BY_USER_SUCCESS: 'CONVERSATION.GET_BY_USER_SUCCESS',
	GET_BY_USER_FAILURE: 'CONVERSATION.GET_BY_USER_FAILURE'
};